name: Clean up Jobs

on:
  workflow_dispatch:
  schedule:
    - cron: "50 1 * * *"

jobs:
  jobprepare:
    name: Prepare for Test
    runs-on: ubuntu-latest
    steps:
      - name: Dayly Artifact Cleanup
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'error'
<<<<<<< HEAD
          min_bytes: '0'
=======
          min_bytes: '0'
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 2
>>>>>>> refs/remotes/origin/main
