# Simple workflow for deploying static content to GitHub Pages
name: Deploy static to Pages

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]
  schedule:
    - cron: "12 4 * * 6"

permissions:
  contents: read
  pages: write
  id-token: write

env:
  BSITE: "d3d3LnF1aW50eXBlLmNvbQo="
  SITE: null
  PATH_ROOT: null

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init Ubuntu
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install gnupg unzip git   wget curl
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: GetHtmls
        id: gethtml
        run: |
          # import key
          echo "${{ secrets.GPG_XSTREAM2 }}" > ${RUNNER_TEMP}/xstream2.key
          gpg --import ${RUNNER_TEMP}/xstream2.key
          # get html
          cd /workdir
          site=`echo ${{ env.BSITE }}|base64 -d`
          echo "SITE=$site" >> $GITHUB_ENV
          PATH_ROOT="/workdir/$site"
          echo "PATH_ROOT=${PATH_ROOT}" >> $GITHUB_ENV
          wget --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15" -q -k -m -np  https://${site}/ || true
          cd ${PATH_ROOT}
          echo "User-agent: *" > robots.txt
          echo "Disallow: /" >> robots.txt
          # add fast
          mkdir -p ${PATH_ROOT}/fast
          echo "fast:`date`" > ${PATH_ROOT}/fast/inde.html
          # 创建用户文件夹
          # 给出不同区域yaml(vms)、json(vls)版本列表
          # 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.PATH_ROOT }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
